# syntax=docker/dockerfile:1.7
#
# warehouse-console depends on @warehouse/ui-kit via `file:../warehouse-ui-kit`
# (a sibling checkout, not a registry package -- see package.json). Build with:
#   docker build --build-context uikit=../warehouse-ui-kit -t warehouse-console .
#
# Endpoints are NO LONGER baked in: src/config.ts resolves every service URL at
# runtime from window.__WAREHOUSE_CONFIG__.apiOrigin, which runtime-config.ts
# fetches from /config.json (mounted from a ConfigMap) before the app mounts.
# One image now serves any environment.
#
# Builder base and install strategy, both deliberate:
#
# 1. node:22-bookworm-slim, not node:26-alpine. This package-lock.json was
#    generated by npm 10 on macOS and carries NO linux entries for the
#    platform-specific optional dependencies Vite 8 pulls in (@rolldown/
#    binding-linux-*, lightningcss-linux-*, @oxlint/binding-linux-*). npm 11
#    (node:26) rejects that outright with EUSAGE "lock file out of sync", and
#    npm's optional-dependency bug (npm/cli#4828) means even a successful
#    `npm ci` leaves the native binding missing, so `vite build` then dies
#    with "Cannot find native binding". Debian/glibc also matches the *-gnu
#    bindings that are actually published.
#
# 2. The lockfile is deliberately NOT used to install, for the same reason:
#    resolving without it is the error message's own prescribed remedy.
#    --no-save plus the rm happening only inside this throwaway build layer
#    means the committed lockfile is never read for resolution nor mutated.

# --- ui-kit build stage (sibling dependency) ---
FROM node:22-bookworm-slim AS uikit-build
WORKDIR /uikit
COPY --from=uikit . .
# The uikit named context is a sibling CHECKOUT and may carry its own
# node_modules holding only the host platform's bindings; strip it (and the
# lockfile) before resolving. warehouse-ui-kit is gaining its own
# .dockerignore, but this stays so the build does not depend on which
# revision happens to be checked out.
RUN --mount=type=cache,target=/root/.npm \
    rm -rf node_modules package-lock.json && npm install --no-save && npm run build

# --- app build stage ---
FROM node:22-bookworm-slim AS build
WORKDIR /workspace/warehouse-ui-kit
COPY --from=uikit-build /uikit/package.json ./package.json
COPY --from=uikit-build /uikit/dist ./dist

WORKDIR /workspace/warehouse-console
COPY package.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm install --no-save
COPY . .
RUN rm -f package-lock.json
RUN npm run build

# --- runtime stage ---
FROM nginxinc/nginx-unprivileged:1.31-alpine
# apk upgrade picks up any CVE fixes published to the 3.21 branch since the
# base image was last rebuilt (openssl, libxml2, etc.), matching the fleet's
# Go-service runtime stages. Root is only needed for this one step.
USER root
RUN apk upgrade --no-cache
USER nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build --chown=nginx:nginx /workspace/warehouse-console/dist /usr/share/nginx/html
EXPOSE 8080
